#Kabanero! on activate substitute StackId for text 'StackId'
apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: StackId-deployment-condition
spec:
  params:
  - name: "event-type"
    type: string
    description: "The Git event type"
  - name: "event-ref"
    type: string
    description: "The Git event ref"
  check:
    name: deployment-condition
    image: kabanero/kabanero-utils@sha256:8020573657ed1b80e2b872a37719d6398ee78219296fe6180733f54425f7bd6a
    command: ["/bin/sh"]
    args:
      - -ce
      - |
        echo $(params.event-type)
        echo $(params.event-ref)
        [[ $(params.event-type) == "push" && $(params.event-ref) == "refs/heads/master" ]]
